language: python
sudo: false
cache: pip

python:
  - "3.5"

install:
  - pip install -r requirements.txt

script:
  - python tests.py

notifications:
  email:
    on_success: change
    on_failure: always
